channels:
  - moble
  - defaults
dependencies:
  - ca-certificates=2017.08.26
  - certifi=2018.1.18
  - intel-openmp=2018.0.0
  - libedit=3.1
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgfortran-ng=7.2.0
  - libstdcxx-ng=7.2.0
  - llvmlite=0.22.0
  - mkl=2018.0.1
  - ncurses=6.0
  - numba=0.37.0
  - numpy=1.14.1
  - openssl=1.0.2n
  - pandas=0.22.0
  - pip=9.0.1
  - python=3.6.4
  - python-dateutil=2.7.0
  - pytz=2018.3
  - readline=7.0
  - scipy=1.0.0
  - setuptools=38.5.1
  - six=1.11.0
  - sqlite=3.22.0
  - tk=8.6.7
  - wheel=0.30.0
  - xz=5.2.3
  - zlib=1.2.11
  - quaternion=2018.03.06.20.03.47
  - pip:
    - numpy-quaternion==2018.3.7.1.23.24
